name: PR

on:
  pull_request:
  workflow_dispatch: # Can run manually from the Actions tab

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions: { contents: read, pull-requests: write }

    steps:
      - uses: actions/checkout@v6

      - uses: git-lfs-hub/ci-cd/actions/init-bun@main

      - run: bun run test-coverage

      - name: Download Main Coverage
        run: |
          mkdir coverage/main
          curl -L https://git-lfs-hub.github.io/server/coverage-summary.json -o coverage/main/coverage-summary.json
          curl -L https://git-lfs-hub.github.io/server/coverage-final.json -o coverage/main/coverage-final.json
        continue-on-error: true

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          file-coverage-mode: changes-affected
          json-summary-compare-path: coverage/main/coverage-summary.json
          threshold-icons: "{90: '🟢', 80: '🟡', 50: '🟠', 1: '🔴', 0: '⬜'}"
