name: PR

on:
  pull_request:
  workflow_dispatch: # Can run manually from the Actions tab

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions: { contents: read, pull-requests: write }

    steps:
      - uses: actions/checkout@v6

      - uses: git-lfs-hub/ci-cd/actions/init-bun@main

      - run: bun run test-coverage

      - name: Report PR Coverage
        uses: davelosert/vitest-coverage-report-action@v2
